#---------------------------------------------------------------------
# Manifest File to create AWS EKS Cluster in Custom VPC
#
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
#
# Copyleft (c) by Denis Astahov 2025
#---------------------------------------------------------------------
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : "demo-eks-cluster"
  version: "1.33"
  region : "ca-central-1"

vpc:
 id     : "vpc-0838edd224de20ca5"
 subnets:
   public:
      ca-central-1a: { id: subnet-03b57e4cd7165579d }  # For Load Balancer
      ca-central-1b: { id: subnet-0a5a978ed589b4cb6 }  # For Load Balancer
   private:
      ca-central-1a: { id: subnet-0be2bb4e6596f8740 }  # For Worker Nodes
      ca-central-1b: { id: subnet-067dedfd6d76477ab }  # For Worker Nodes

managedNodeGroups:
  - name             : worker-group-1
    instanceType     : t3.small
    desiredCapacity  : 2
    labels           : { role: worker1 }   
    volumeSize       : 20                              # Minimum 20GB
    privateNetworking: true